[package]
name = "hackernews_tui"
version = "0.1.0"
authors = ["Thang Pham <phamducthang1234@gmail.com>"]
edition = "2018"

[dependencies]
cursive = { version = "0.16", default-features = false, features = ["crossterm-backend"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }