[package]
name = "hackernews_tui"
version = "0.1.0"
authors = ["Thang Pham <phamducthang1234@gmail.com>"]
edition = "2018"

[dependencies]
cursive = { version = "0.16", default-features = false, features = ["crossterm-backend", "toml", "markdown"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
rayon = "1.5"
log = "0.4"
env_logger = "0.8"
htmlescape = "0.3"
regex = "1"