# "page_scrolling" is a feature that enables page-like behavior when navigating.
# The application will automatically adjust the View based on the scrolling direction.
page_scrolling = true

[client.story_pooling]
# "story_pooling" is a feature that allows the application to fetch stories
# in background and store them in cache memory.
enable = true
# delay (in seconds) between two story API requests
delay = 2
# possible values for allows:
# - "front_page" -> "Story View - Front Page"
# - "story" -> "Story View - All Stories"
# - "ask_hn" -> "Story View - Ask HN"
# - "show_hn" -> "Story View - Show HN"
# - "job" -> "Story View - Jobs"
allows = ["front_page"]

[client]
# "client_timeout" is the application Client timeout (in seconds) when making an API request
client_timeout = 16

[client.story_limit]
# "story_limit" stores the number of maximum stories displayed in a page in each View
search = 10
front_page = 25

[theme]
# cursive's palette color
# (more information can be found in https://docs.rs/cursive/0.16.3/cursive/theme/index.html)
background = "#f6f6ef"
shadow = "black"
view = "#f6f6ef"
primary = "#4a4a48"
secondary = "#a5a5a5"
tertiary = "white"
title_primary = "black"
title_secondary = "yellow"
highlight = "#6c6c6c"
highlight_inactive = "blue"
highlight_text = "white"

# "additional" colors defined by the application
# "link_text" is a text color for a URL
# "link_id" is a background color for `link_id` in CommentView
# "search_highlight_bg" is a background color for matched search
# "status_bar_bg" is a background color for the status bar
# "code_block_bg" is a background color for a code block
link_text = "#4fbbfd"
link_id_bg = "#ffff00"
search_highlight_bg = "#ffff00"
status_bar_bg = "#ff6600"
code_block_bg = "#c8c8c8"
